### ISSUE TITLE
fix emoji images

### ISSUE THREAD

**Issue by aogaili** [insanum/obsidian_gruvbox#19] opened 2021-10-18 05:47 UTC
The emoji are not showing up correctly. 

I had to add the following line to override the img block command.

```
img.emoji {
    display: inline-block !important;
}

```

**Comment by insanum** [comment] 2021-11-08 03:34
I'm unable to reproduce. I think this was fixed indirectly by a previous commit that modified the img style.

**Closed by insanum** 2021-11-08 03:34 UTC
